export default {
  alignContent: ['stretch', 'center', 'flexStart', 'flexEnd', 'spaceBetween', 'spaceAround'],
  alignItems: ['stretch', 'center', 'flexStart', 'flexEnd', 'baseline'],
  alignSelf: ['stretch', 'center', 'flexStart', 'flexEnd', 'baseline'],
  backgroundAttachment: ['scroll', 'fixed', 'local'],
  backgroundRepeat: ['repeat', 'repeatX', 'repeatY', 'noRepeat', 'initial', 'inherit'],
  backgroundSize: ['auto', 'length', 'cover', 'contain', 'initial', 'inherit'],
  borderBottomStyle: ['dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderLeftStyle: ['dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderRightStyle: ['dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderStyle: ['dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  borderTopStyle: ['dotted', 'dashed', 'solid', 'double', 'groove', 'ridge', 'inset', 'outset'],
  clear: ['left', 'right', 'both'],
  cursor: [
    'alias',
    'allScroll',
    'cell',
    'contextMenu',
    'colResize',
    'copy',
    'crosshair',
    'eResize',
    'ewResize',
    'grab',
    'grabbing',
    'help',
    'move',
    'nResize',
    'neResize',
    'neswResize',
    'nsResize',
    'nwResize',
    'nwResize',
    'nwseResize',
    'noDrop',
    'none',
    'notAllowed',
    'pointer',
    'progress',
    'rowResize',
    'sResize',
    'seResize',
    'swResize',
    'text',
    'verticalText',
    'wResize',
    'wait',
    'zoomIn',
    'zoomOut',
  ],
  display: [
    'block',
    'flex',
    'inherit',
    'initial',
    'inline',
    'inline-block',
    'inline-flex',
    'inline-table',
    'list-item',
    'none',
    'run-in',
    'table',
    'table-caption',
    'table-cell',
    'table-column',
    'table-column-group',
    'table-footer-group',
    'table-header-group',
    'table-row',
    'table-row-group',
  ],
  direction: ['ltr', 'rtl'],
  flexDirection: ['row', 'rowReverse', 'column', 'columnReverse'],
  flexWrap: ['nowrap', 'wrap', 'wrapReverse'],
  float: ['left', 'right'],
  fontFamily: [
    'Alegreya',
    'Alegreya Sans',
    'Anonymous Pro',
    'Archivo Narrow',
    'Arvo',
    'BioRhyme',
    'Bitter',
    'Cabin',
    'Cardo',
    'Chivo',
    'Cormorant',
    'Crimson Text',
    'Domine',
    'Eczar',
    'Fira Sans',
    'Gentium Basic',
    'Inconsolata',
    'Karla',
    'Lato',
    'Libre Baskerville',
    'Libre Franklin',
    'Lora',
    'Merriweather',
    'Montserrat',
    'Neuton',
    'Old Standard TT',
    'Open Sans',
    'Playfair Display',
    'Poppins',
    'PT Sans',
    'PT Serif',
    'Rajdhani',
    'Raleway',
    'Roboto',
    'Roboto Slab',
    'Rubik',
    'Source Sans Pro',
    'Source Serif Pro',
    'Space Mono',
    'Work Sans',
  ],
  fontStyle: ['normal', 'italic', 'oblique'],
  fontVariant: ['normal', 'small-caps'],
  fontWeight: [
    'normal',
    'bold',
    'bolder',
    'lighter',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
  ],
  justifyContent: ['flexStart', 'flexEnd', 'center', 'spaceBetween', 'spaceAround'],
  listStylePosition: ['inside', 'outside'],
  listStyleType: [
    'disc',
    'armenian',
    'circle',
    'cjkIdeographic',
    'decimal',
    'decimalLeadingZero',
    'georgian',
    'hebrew',
    'hiragana',
    'hiraganaIroha',
    'katakana',
    'katakanaIroha',
    'lowerAlpha',
    'lowerGreek',
    'lowerLatin',
    'lowerRoman',
    'none',
    'square',
    'upperAlpha',
    'upperLatin',
    'upperRoman',
  ],
  overflow: ['visible', 'hidden', 'scroll', 'auto'],
  pageBreakAfter: ['always', 'avoid', 'left', 'righ'],
  pageBreakBefore: ['always', 'avoid', 'left', 'righ'],
  position: ['absolute', 'fixed', 'relative'],
  textAlign: ['left', 'right', 'center', 'justify'],
  textDecoration: ['underline', 'overline', 'lineThrough'],
  textTransform: ['capitalize', 'uppercase', 'lowercase'],
  verticalAlign: ['baseline', 'sub', 'super', 'top', 'textTop', 'middle', 'bottom', 'textBottom'],
  visibility: ['visible', 'hidden'],
};
