/**
 * @see http://www.zeali.net/mirrors/w3cshool/css/default.asp.html
 */
export default {
  items: [
    {
      name: 'Background',
      subItems: [
        'backgroundAttachment',
        'backgroundBlendMode',
        'backgroundClip',
        'backgroundColor',
        'backgroundImage',
        'backgroundOrigin',
        'backgroundPosition',
        'backgroundRepeat',
        'backgroundSize',
      ],
    },
    {
      name: 'Border',
      subItems: [
        'borderBottomColor',
        'borderBottomLeftRadius',
        'borderBottomRightRadius',
        'borderBottomStyle',
        'borderBottomWidth',
        'borderColor',
        'borderLeftColor',
        'borderLeftStyle',
        'borderLeftWidth',
        'borderRadius',
        'borderRightColor',
        'borderRightStyle',
        'borderRightWidth',
        'borderStyle',
        'borderTopColor',
        'borderTopLeftRadius',
        'borderTopRightRadius',
        'borderTopStyle',
        'borderTopWidth',
        'borderWidth',
      ],
    },
    {
      name: 'Classification and Positioning',
      subItems: [
        'alignContent',
        'alignItems',
        'alignSelf',
        'bottom',
        'clear',
        'display',
        'flexBasis',
        'flexDirection',
        'flexGrow',
        'flexShrink',
        'flexWrap',
        'float',
        'justifyContent',
        'left',
        'overflow',
        'overflowX',
        'overflowY',
        'position',
        'right',
        'top',
        'verticalAlign',
        'visibility',
        'zIndex',
      ],
    },
    {
      name: 'Dimension',
      subItems: [
        'height',
        'maxHeight',
        'maxWidth',
        'minHeight',
        'minWidth',
        'width',
      ],
    },
    {
      name: 'Font',
      subItems: [
        'fontFamily',
        'fontSize',
        'fontStyle',
        'fontVariant',
        'fontWeight',
      ],
    },
    {
      name: 'Margin',
      subItems: [
        'margin',
        'marginBottom',
        'marginLeft',
        'marginRight',
        'marginTop',
      ],
    },
    {
      name: 'Padding',
      subItems: [
        'padding',
        'paddingBottom',
        'paddingLeft',
        'paddingRight',
        'paddingTop',
      ],
    },
    {
      name: 'Text',
      subItems: [
        'color',
        'direction',
        'lineHeight',
        'letterSpacing',
        'textAlign',
        'textDecoration',
        'textIndent',
        'textOverflow',
        'textShadow',
        'textTransform',
        'whiteSpace',
        'wordBreak',
        'wordSpacing',
        'wordWrap',
      ],
    },
  ],
};
