/**
 * svg attributes with options
 * @see https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/???
 */
export default {
  accumulate: ['none', 'sum'],
  additive: ['replace', 'sum'],
  alignmentBaseline: [
    'auto',
    'baseline',
    'before-edge',
    'text-before-edge',
    'middle',
    'central',
    'after-edge',
    'text-after-edge',
    'ideographic',
    'alphabetic',
    'hanging',
    'mathematical',
    'inherit',
  ],
  attributeType: ['CSS', 'XML', 'auto'],
  baselineShift: [
    'auto',
    'baseline',
    'super',
    'sub',
    'inherit',
  ],
  calcMode: [
    'discrete',
    'linear',
    'paced',
    'spline',
  ],
  clipPathUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  clipRule: [
    'nonzero',
    'evenodd',
    'inherit',
  ],
  colorInterpolation: [
    'auto',
    'sRGB',
    'linearRGB',
    'inherit',
  ],
  colorInterpolationFilters: [
    'auto',
    'sRGB',
    'linearRGB',
    'inherit',
  ],
  colorProfile: [
    'auto',
    'sRGB',
    'inherit',
  ],
  colorRendering: [
    'auto',
    'optimizeSpeed',
    'optimizeQuality',
    'inherit',
  ],
  cursor: [
    'auto',
    'crosshair',
    'default',
    'pointer',
    'move',
    'e-resize',
    'ne-resize',
    'nw-resize',
    'n-resize',
    'se-resize',
    'sw-resize',
    's-resize',
    'w-resize',
    'text',
    'wait',
    'help',
    'inherit',
  ],
  direction: ['ltr', 'rtl', 'inherit'],
  display: [
    'inline',
    'block',
    'list-item',
    'run-in',
    'compact',
    'marker',
    'table',
    'inline-table',
    'table-row-group',
    'table-header-group',
    'table-footer-group',
    'table-row',
    'table-column-group',
    'table-column',
    'table-cell',
    'table-caption',
    'none',
    'inherit',
  ],
  dominantBaseline: [
    'auto',
    'use-script',
    'no-change',
    'reset-size',
    'ideographic',
    'alphabetic',
    'hanging',
    'mathematical',
    'central',
    'middle',
    'text-after-edge',
    'text-before-edge',
    'inherit',
  ],
  edgeMode: [
    'duplicate',
    'wrap',
    'none',
  ],
  fillRule: [
    'nonzero',
    'evenodd',
    'inherit',
  ],
  filterUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  floodColor: [
    'currentColor',
    'inherit',
  ],
  fontStretch: [
    'normal',
    'wider',
    'narrower',
    'ultra-condensed',
    'extra-condensed',
    'condensed',
    'semi-condensed',
    'semi-expanded',
    'expanded',
    'extra-expanded',
    'ultra-expanded',
    'inherit',
  ],
  fontStyle: [
    'normal',
    'italic',
    'oblique',
    'inherit',
  ],
  fontVariant: [
    'normal',
    'small-caps',
    'inherit',
  ],
  fontWeight: [
    'normal',
    'bold',
    'bolder',
    'lighter',
    '100',
    '200',
    '300',
    '400',
    '500',
    '600',
    '700',
    '800',
    '900',
    'inherit',
  ],
  gradientUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  imageRendering: [
    'auto',
    'optimizeSpeed',
    'optimizeQuality',
    'inherit',
  ],
  in: [
    'SourceGraphic',
    'SourceAlpha',
    'BackgroundImage',
    'BackgroundAlpha',
    'FillPaint',
    'StrokePaint',
  ],
  in2: [
    'SourceGraphic',
    'SourceAlpha',
    'BackgroundImage',
    'BackgroundAlpha',
    'FillPaint',
    'StrokePaint',
  ],
  markerUnits: [
    'userSpaceOnUse',
    'strokeWidth',
  ],
  maskContentUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  maskUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  mode: [
    'normal',
    'multiply',
    'screen',
    'darken',
    'lighten',
  ],
  operator: [
    'over',
    'in',
    'out',
    'atop',
    'xor',
    'arithmetic',
    ' erode',
    'dilate',
  ],
  overflow: [
    'visible',
    'hidden',
    'scroll',
    'auto',
    'inherit',
  ],
  paintOrder: [
    'normal',
    'fill',
    'stroke',
    'markers',
    'inherit',
  ],
  patternContentUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  patternUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  pointerEvents: [
    'visiblePainted',
    'visibleFill',
    'visibleStroke',
    'visible',
    'painted',
    'fill',
    'stroke',
    'all',
    'none',
    'inherit',
  ],
  preserveAspectRatio: [
    'none',
    'xMinYMin',
    'xMidYMin',
    'xMaxYMin',
    'xMinYMid',
    'xMidYMid',
    'xMaxYMid',
    'xMinYMax',
    'xMidYMax',
    'xMaxYMax',
    'meet',
    'slice',
  ],
  primitiveUnits: [
    'userSpaceOnUse',
    'objectBoundingBox',
  ],
  repeatCount: [
    'indefinite',
    '1',
    '2',
    '3',
    '4',
    '5',
    '6',
    '7',
    '8',
    '9',
    '10',
  ],
  restart: [
    'always',
    'whenNotActive',
    'never',
  ],
  shapeRendering: [
    'auto',
    'optimizeSpeed',
    'crispEdges',
    'geometricPrecision',
    'inherit',
  ],
  stitchTiles: [
    'noStitch',
    'stitch',
  ],
  strokeLinecap: [
    'butt',
    'round',
    'square',
    'inherit',
  ],
  strokeLinejoin: [
    'miter',
    'round',
    'bevel',
    'inherit',
  ],
  textAnchor: [
    'start',
    'middle',
    'end',
    'inherit',
  ],
  textDecoration: [
    'none',
    'underline',
    'overline',
    'line-through',
    'blink',
    'inherit',
  ],
  textRendering: [
    'auto',
    'optimizeSpeed',
    'optimizeLegibility',
    'geometricPrecision',
    'inherit',
  ],
  type: [
    // For the <animatetransform> elements
    'translate',
    'scale',
    'rotate',
    'skewX',
    'skewY',
    // For the <fecolormatrix> element
    'matrix',
    'saturate',
    'hueRotate',
    'luminanceToAlpha',
    // For the <fefuncr>, <fefuncg>, <fefuncb>, and <fefunca> elements
    'identity',
    'table',
    'discrete',
    'linear',
    'gamma',
    // For the <feturbulence> element
    'fractalNoise',
    'turbulence',
    // For the <style> and <script> elements
    'script',
    'style',
  ],
  version: [
    1.0, 1.1,
  ],
  visibility: [
    'visible',
    'hidden',
    'collapse',
    'inherit',
  ],
  writingMode: [
    'lr-tb',
    'rl-tb',
    'tb-rl',
    'lr',
    'rl',
    'tb',
    'inherit',
  ],
  xChannelSelector: [
    'R',
    'G',
    'B',
    'A',
  ],
  yChannelSelector: [
    'R',
    'G',
    'B',
    'A',
  ],
};
