import {
  STRING,
  NUMBER,
  ENUM,
} from '../propertyTypes';
/**
 * all css
 */
export default {
  alignContent: ENUM,
  alignItems: ENUM,
  alignSelf: ENUM,
  backgroundAttachment: ENUM,
  backgroundColor: STRING,
  backgroundImage: STRING,
  backgroundPosition: STRING,
  backgroundRepeat: ENUM,
  backgroundSize: ENUM,
  borderBottomColor: STRING,
  borderBottomStyle: ENUM,
  borderBottomWidth: NUMBER,
  borderColor: STRING,
  borderLeftColor: STRING,
  borderLeftStyle: ENUM,
  borderLeftWidth: NUMBER,
  borderRadius: NUMBER,
  borderRightColor: STRING,
  borderRightStyle: ENUM,
  borderRightWidth: NUMBER,
  borderStyle: ENUM,
  borderTopColor: STRING,
  borderTopStyle: ENUM,
  borderTopWidth: NUMBER,
  borderWidth: NUMBER,
  bottom: NUMBER,
  clear: ENUM,
  color: STRING,
  cursor: ENUM,
  display: ENUM,
  flexDirection: ENUM,
  flexWrap: ENUM,
  flexGrow: NUMBER,
  flexShrink: NUMBER,
  flexBasis: NUMBER,
  float: ENUM,
  fontFamily: ENUM,
  fontSize: NUMBER,
  fontWeight: ENUM,
  height: STRING,
  justifyContent: ENUM,
  left: NUMBER,
  letterSpacing: NUMBER,
  lineHeight: NUMBER,
  listStyleImage: STRING,
  listStylePosition: ENUM,
  listStyleType: ENUM,
  margin: NUMBER,
  marginBottom: NUMBER,
  marginLeft: NUMBER,
  marginRight: NUMBER,
  marginTop: NUMBER,
  maxHeight: NUMBER,
  maxWidth: NUMBER,
  minHeight: NUMBER,
  minWidth: NUMBER,
  overflow: ENUM,
  padding: NUMBER,
  paddingBottom: NUMBER,
  paddingLeft: NUMBER,
  paddingRight: NUMBER,
  paddingTop: NUMBER,
  pageBreakAfter: ENUM,
  pageBreakBefore: ENUM,
  position: ENUM,
  right: NUMBER,
  textAlign: ENUM,
  textDecoration: ENUM,
  textIndent: NUMBER,
  textTransform: ENUM,
  top: NUMBER,
  verticalAlign: ENUM,
  visibility: ENUM,
  width: STRING,
  zIndex: NUMBER,
};
