export default {
  grid: {
    /*
    clear default css (generated by real-time code) to avoid fit full screen (fix bug)
    lock this value to avoid adjust
     */
    width: 'calc(100% - 16px)', // lock this value, don't let user use
    padding: '8px', // at least 8px, for dbclick event, visible
  },
  row: {
    margin: 0, // clear default css to avoid overflow (fix bug)
  },
  col: {
    minHeight: '24px', // for visible
    cursor: 'auto',
    flexWrap: 'wrap',
  },
  colDirectionHCSS: {
    flexDirection: 'column',
    display: 'flex',
  },
  colDirectionVCSS: {
    flexDirection: 'row',
    display: 'flex',
  },

  colCSS: `background-color:
    rgba(255, 255, 255, 0.75);`,

  colCSSOdd: `background-color:
    rgba(255, 255, 255, 0.75);`,

  colCSSEven: `background-color:
    rgba(250, 250, 250, 0.75);`,

  colDirectionHHoverCSS: `background:
    repeating-linear-gradient(
      90deg, rgba(224, 224, 224, .5),
      rgba(224, 224, 224, .5) 8px,
      rgba(245, 245, 245, .5) 8px,
      rgba(245, 245, 245, .5) 16px);`,

  colDirectionVHoverCSS: `background:
    repeating-linear-gradient(
      0deg, rgba(224, 224, 224, .5),
      rgba(224, 224, 224, .5) 8px,
      rgba(245, 245, 245, .5) 8px,
      rgba(245, 245, 245, .5) 16px);`,
  /*
  col align with other
   */
  colAlignTop: {
    alignSelf: 'flex-start',
  },
  colAlignCenter: {
    alignSelf: 'center',
  },
  colAlignBottom: {
    alignSelf: 'flex-end',
  },
  colDirectionH: {
    flexDirection: 'column',
    display: 'flex',
  },
  colDirectionV: {
    flexDirection: 'row',
    display: 'flex',
  },
  /*
  content position
  base on -> flex-direction: row;
   */
  positionTLInRow: { // top-left
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  positionMLInRow: { // middle-left
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  positionBLInRow: { // bottom-left
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  positionTMInRow: { // top-middle
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'center',
  },
  positionCInRow: { // center
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  positionBMInRow: { // bottom-middle
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'center',
  },
  positionTRInRow: { // top-right
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  positionMRInRow: { // middle-right
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  positionBRInRow: { // bottom-right
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  /*
  content position
  base on -> flex-direction: column;
   */
  positionTLInColumn: { // top-left
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  positionMLInColumn: { // middle-left
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'center',
  },
  positionBLInColumn: { // bottom-left
    alignItems: 'flex-start',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  positionTMInColumn: { // top-middle
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  positionCInColumn: { // center
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'center',
  },
  positionBMInColumn: { // bottom-middle
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  positionTRInColumn: { // top-right
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'flex-start',
  },
  positionMRInColumn: { // middle-right
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'center',
  },
  positionBRInColumn: { // bottom-right
    alignItems: 'flex-end',
    display: 'flex',
    justifyContent: 'flex-end',
  },
  /*
  colorful
   */
  direction45: {
    background: `repeating-linear-gradient(
      45deg, rgba(224, 224, 224, .5),
      rgba(224, 224, 224, .5) 8px,
      rgba(245, 245, 245, .5) 8px,
      rgba(245, 245, 245, .5) 16px)`,
  },
  directionV: {
    background: `repeating-linear-gradient(
      0deg, rgba(224, 224, 224, .5),
      rgba(224, 224, 224, .5) 8px,
      rgba(245, 245, 245, .5) 8px,
      rgba(245, 245, 245, .5) 16px)`,
  },
  directionH: {
    background: `repeating-linear-gradient(
      90deg, rgba(224, 224, 224, .5),
      rgba(224, 224, 224, .5) 8px,
      rgba(245, 245, 245, .5) 8px,
      rgba(245, 245, 245, .5) 16px)`,
  },
  directionGrid: {
    background: `repeating-linear-gradient(
        90deg, rgba(224, 224, 224, .5),
        rgba(224, 224, 224, .5) 8px,
        rgba(245, 245, 245, .5) 8px,
        rgba(245, 245, 245, .5) 16px
      ),
      repeating-linear-gradient(
        0deg, rgba(224, 224, 224, .5),
        rgba(224, 224, 224, .5) 8px,
        rgba(245, 245, 245, .5) 8px,
        rgba(245, 245, 245, .5) 16px
      )`,
  },
};
